sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: XNyvKwbrOsJoOeAVQXuUhZ5Qtprzvl
    access-key-id: LTAI5tNQbkaNeaPzuBNxaT8n
    bucket-name: jollytang
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wx991382aba31a7458
    secret: c4c4b87f8f050c43caea4b7d40a4f7e7